bad_w =[
    "abestada", "abestado",
    "anta",
    "babaca",
    "baranga",
    "besta",
    "bicha",
    "bocal", "boçal",
    "boiola",
    "broxa",
    "burra", "burro",
    "cacete",
    "cafetao", "cafetão",
    "cagao", "cagão", "cagona",
    "canalha",
    "capeta",
    "caralho",
    "chata", "chato",
    "cinica", "cínica", "cinico", "cínico",
    "corna", "corno",
    "corrupta", "corrupto",
    "covarde",
    "cretina", "cretino",
    "criminosa", "criminoso",
    "debil mental", "debil-mental", "débil mental", "débil-mental",
    "depravada", "depravado",
    "desaforada", "desaforado",
    "descarada", "descarado",
    "desonesta", "desonesto",
    "desprezivel", "desprezível",
    "diaba", "diabo",
    "dissimulada", "dissimulado",
    "doida", "doido",
    "duro",
    "egoista", "egoísta",
    "estupida", "estúpida", "estupido", "estúpido",
    "excomungada", "excomungado",
    "falsa", "falso",
    "fedorenta", "fedorento",
    "feia", "feio",
    "filha da mae", "filha da mãe", "filhas da mae", "filhas da mãe",
    "filho da mae", "filho da mãe", "filhos da mae", "filhos da mãe",
    "filha da puta", "filhas da puta", "filho da puta", "filhos da puta",
    "filho duma egua", "filho duma égua", "filho duma ègua", "filho duma Ègua",
    "fingida", "fingido",
    "fracassada", "fracassado",
    "frouxa", "frouxo",
    "gananciosa", "ganancioso",
    "gentalha",
    "gorda", "gordo",
    "grossa", "grosso",
    "hipocrita", "hipócrita",
    "horrorosa", "horroroso",
    "horrivel", "horrível",
    "idiota",
    "ignorante",
    "imbecil",
    "imprestavel", "imprestável", "imprestaveis", "imprestáveis",
    "inutil", "inútil",
    "insignificante",
    "jaburu",
    "jacu",
    "joao ninguem", "joão ninguem", "joao ninguém", "joão ninguém",
    "jumento",
    "ladra", "ladrao", "ladrão",
    "lambisgoia", "lambisgóia",
    "larapia", "larápia", "larapio", "larápio",
    "largada", "largado",
    "lazarenta", "lazarento",
    "lenta", "lento",
    "lerda", "lerdo",
    "lesada", "lesado",
    "lixo",
    "lunatica", "lunática", "lunatico", "lunático",
    "mal acabada", "mal acabado", "mau acabada", "mau acabado",
    "mal comida", "mal-comida", "mau comida", "mau-comida",
    "mal carater", "mal caráter", "mau carater", "mau caráter",
    "mal-carater", "mal-caráter", "mau-carater", "mau-caráter",
    "mala",
    "malandra", "malandro",
    "maldita", "maldito",
    "mandao", "mandão", "mandona",
    "mao de vaca", "mão de vaca", "mao-de-vaca", "mão-de-vaca",
    "merda",
    "mesquinha", "mesquinho",
    "miseravel", "miserável",
    "mongol",
    "monstra", "monstro",
    "mosca morta", "mosca-morta",
    "nojenta", "nojento",
    "obscena", "obsceno",
    "otaria", "otária", "otario", "otário",
    "palhaca", "palhaça", "palhacada", "palhaçada", "palhaco", "palhaço",
    "panaca",
    "pangare", "pangaré",
    "parasita",
    "paspalha", "paspalho",
    "patife",
    "pao duro", "pão duro", "pao-duro", "pão-duro",
    "periguete", "piriguete",
    "pervertida", "pervertido",
    "pessimo", "péssimo", "pèssimo",
    "peste",
    "pilantra",
    "piranha",
    "porca", "porco",
    "porcaria",
    "porra",
    "praga",
    "preguicosa", "preguiçosa", "preguicoso", "preguiçoso",
    "problema",
    "puta", "puta merda",
    "puto",
    "ranheta",
    "ranzinza",
    "rapariga",
    "rato",
    "recalcada",
    "relaxada", "relaxado",
    "reles",
    "repugnante",
    "repulsiva", "repulsivo",
    "retardada", "retardado",
    "ridicula", "ridícula", "ridiculo", "ridículo",
    "rude",
    "ruim",
    "sacana",
    "safada", "safado",
    "salafraria", "salafrária", "salafrario", "salafrário",
    "saliente",
    "sata", "satã",
    "satans", "satanás",
    "sebosa", "seboso",
    "sem vergonha", "sem-vergonha", "sem vergonho", "sem-vergonho",
    "suja", "sujo",
    "tapada", "tapado",
    "tinhosa", "tinhoso",
    "traira", "traíra",
    "traidor", "traidora",
    "traste",
    "trouxa",
    "ultrapassada", "ultrapassado",
    "vadia", "vadio",
    "vagabunda", "vagabundo",
    "vai se fode", "vai se foder",
    "vai tomar no cu",
    "viada", "viado",
    "xucra", "xucro",
    "zero a esquerda", "zero à esquerda"
]